version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Installing dependencies"
      - npm pkg delete scripts.prepare
      - rm -rf node_modules
      - rm -f package-lock.json
      - npm install
      - echo "Verifying lucide-react installation"
      - npm list lucide-react
      - ls -la node_modules/lucide-react/
  build:
    commands:
      - echo "Building the project"
      - node --version
      - npm --version
      - npm run build
  post_build:
    commands:
      - echo "Uploading artifacts to S3"
      - aws s3 sync --delete ./dist s3://${S3_BUCKET_NAME}
      - echo "Invalidating CloudFront distribution"
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/index.html"
