/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _publicRouteRouteImport } from './routes/__public/route'
import { Route as _privateRouteRouteImport } from './routes/__private/route'
import { Route as _publicIndexRouteImport } from './routes/__public/index'
import { Route as _publicAboutRouteImport } from './routes/__public/about'
import { Route as _privateDashboardRouteImport } from './routes/__private/dashboard'
import { Route as _publicProjectsRouteRouteImport } from './routes/__public/projects/route'
import { Route as _publicProjectsProjectIdRouteImport } from './routes/__public/projects/$projectId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicRouteRoute = _publicRouteRouteImport.update({
  id: '/__public',
  getParentRoute: () => rootRouteImport,
} as any)
const _privateRouteRoute = _privateRouteRouteImport.update({
  id: '/__private',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicIndexRoute = _publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _publicRouteRoute,
} as any)
const _publicAboutRoute = _publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => _publicRouteRoute,
} as any)
const _privateDashboardRoute = _privateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _privateRouteRoute,
} as any)
const _publicProjectsRouteRoute = _publicProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => _publicRouteRoute,
} as any)
const _publicProjectsProjectIdRoute =
  _publicProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => _publicProjectsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/projects': typeof _publicProjectsRouteRouteWithChildren
  '/dashboard': typeof _privateDashboardRoute
  '/about': typeof _publicAboutRoute
  '/': typeof _publicIndexRoute
  '/projects/$projectId': typeof _publicProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/projects': typeof _publicProjectsRouteRouteWithChildren
  '/dashboard': typeof _privateDashboardRoute
  '/about': typeof _publicAboutRoute
  '/': typeof _publicIndexRoute
  '/projects/$projectId': typeof _publicProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__private': typeof _privateRouteRouteWithChildren
  '/__public': typeof _publicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/__public/projects': typeof _publicProjectsRouteRouteWithChildren
  '/__private/dashboard': typeof _privateDashboardRoute
  '/__public/about': typeof _publicAboutRoute
  '/__public/': typeof _publicIndexRoute
  '/__public/projects/$projectId': typeof _publicProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/projects'
    | '/dashboard'
    | '/about'
    | '/'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/projects'
    | '/dashboard'
    | '/about'
    | '/'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/__private'
    | '/__public'
    | '/login'
    | '/__public/projects'
    | '/__private/dashboard'
    | '/__public/about'
    | '/__public/'
    | '/__public/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _privateRouteRoute: typeof _privateRouteRouteWithChildren
  _publicRouteRoute: typeof _publicRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public': {
      id: '/__public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__private': {
      id: '/__private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public/': {
      id: '/__public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _publicIndexRouteImport
      parentRoute: typeof _publicRouteRoute
    }
    '/__public/about': {
      id: '/__public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof _publicAboutRouteImport
      parentRoute: typeof _publicRouteRoute
    }
    '/__private/dashboard': {
      id: '/__private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _privateDashboardRouteImport
      parentRoute: typeof _privateRouteRoute
    }
    '/__public/projects': {
      id: '/__public/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof _publicProjectsRouteRouteImport
      parentRoute: typeof _publicRouteRoute
    }
    '/__public/projects/$projectId': {
      id: '/__public/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof _publicProjectsProjectIdRouteImport
      parentRoute: typeof _publicProjectsRouteRoute
    }
  }
}

interface _privateRouteRouteChildren {
  _privateDashboardRoute: typeof _privateDashboardRoute
}

const _privateRouteRouteChildren: _privateRouteRouteChildren = {
  _privateDashboardRoute: _privateDashboardRoute,
}

const _privateRouteRouteWithChildren = _privateRouteRoute._addFileChildren(
  _privateRouteRouteChildren,
)

interface _publicProjectsRouteRouteChildren {
  _publicProjectsProjectIdRoute: typeof _publicProjectsProjectIdRoute
}

const _publicProjectsRouteRouteChildren: _publicProjectsRouteRouteChildren = {
  _publicProjectsProjectIdRoute: _publicProjectsProjectIdRoute,
}

const _publicProjectsRouteRouteWithChildren =
  _publicProjectsRouteRoute._addFileChildren(_publicProjectsRouteRouteChildren)

interface _publicRouteRouteChildren {
  _publicProjectsRouteRoute: typeof _publicProjectsRouteRouteWithChildren
  _publicAboutRoute: typeof _publicAboutRoute
  _publicIndexRoute: typeof _publicIndexRoute
}

const _publicRouteRouteChildren: _publicRouteRouteChildren = {
  _publicProjectsRouteRoute: _publicProjectsRouteRouteWithChildren,
  _publicAboutRoute: _publicAboutRoute,
  _publicIndexRoute: _publicIndexRoute,
}

const _publicRouteRouteWithChildren = _publicRouteRoute._addFileChildren(
  _publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _privateRouteRoute: _privateRouteRouteWithChildren,
  _publicRouteRoute: _publicRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
