// Auto-generated by: npm run db:types
// Run after applying migrations: supabase gen types typescript --local > src/lib/types/database.types.ts
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
