name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run ci:lint

      - name: Run types
        run: npm run ci:types

      - name: Run tests
        run: npm run ci:test
